### ISSUE TITLE
Discord bot to enter into a raffle!

### ISSUE THREAD

**Issue by pyronlaboratory** [SaxyPandaBear/raffle_bot#1]
Hi SaxyPandaBear,

(Well I never imagined myself saying that! Anywho)

I've recently got into discord and I'm really impressed with your code. This is by far the most neat piece I saw on the GitHub.

I would really appreciate if you could help me figure out a few bits here;

>> This script only works for raffle hosted on discord servers? Yes/No.

If Yes, can I also create a discord bot to enter raffles around the globe, and not just on discord servers ( like on various websites.. )

>> The bot acts a raffle manager here? Yes/No.

If Yes, can I also create a bot who acts as a participant in these raffle?
 
How do we go about this requirement?

Thanks mate,
Ronnie

**Comment by SaxyPandaBear** [comment]
I'm not the person you should be looking to for how to make your own raffle bot with your own requirements.

**Comment by pyronlaboratory** [comment]
My SaxyPandaBear,

We obviously didn't communicate clearly in the last thread. I was not asking you to do my work, but since you had the lead on this subject, I just wanted to get some guidance.

Now while you were busy thinking about belittling me with your arrogant reply, I did my own research and figured out the way to proceed.

Anyways I've loads of work to do, so peace out for now!

Ronnie
